// Copyright (C) 2026 Michał Szymański
// SPDX-License-Identifier: AGPL-3.0-or-later
// See NOTICE for the additional term under section 7(b): the attribution this
// program prints must be preserved.

package io.mszymanski.orknux.cli

import picocli.AutoComplete
import picocli.CommandLine
import picocli.CommandLine.Command
import picocli.CommandLine.Model.CommandSpec
import picocli.CommandLine.ParameterException
import picocli.CommandLine.Parameters
import picocli.CommandLine.Spec
import java.util.concurrent.Callable

/** The shells this can write a completion script for. */
enum class CompletionShell {
    /** Also what zsh uses, after `autoload -U +X bashcompinit && bashcompinit`. */
    BASH,
    ZSH,
    POWERSHELL,
}

/**
 * `orkx completion <shell>` — a script that completes subcommands and options.
 *
 * Printed rather than installed: where a shell reads its completions from is the shell's
 * business and the reader's, and a CLI that writes into somebody's profile uninvited is a CLI
 * that has to be forgiven.
 *
 * Bash comes from picocli, which generates it from the same command tree the parser uses.
 * PowerShell picocli does not do, and on Windows that is the shell people are actually in — so
 * it is generated here from that same tree, which is what keeps both honest as commands
 * are added.
 */
@Command(
    name = "completion",
    mixinStandardHelpOptions = true,
    description = ["Print a shell completion script."],
    optionListHeading = "%nOptions:%n",
    sortOptions = false,
)
class CompletionCommand : Callable<Int> {

    @Spec
    lateinit var spec: CommandSpec

    @Parameters(
        index = "0",
        paramLabel = "SHELL",
        description = ["bash, zsh or powershell."],
    )
    var shell: CompletionShell? = null

    override fun call(): Int {
        val out = spec.commandLine().out
        val root = spec.root().commandLine()

        when (shell) {
            // One script for both: picocli's own, which zsh reads after bashcompinit.
            CompletionShell.BASH, CompletionShell.ZSH -> out.print(AutoComplete.bash(root.commandName, root))
            CompletionShell.POWERSHELL -> out.print(powershell(root))
            null -> throw ParameterException(spec.commandLine(), "Which shell? bash, zsh or powershell.")
        }
        out.flush()
        return ExitCode.OK
    }

    /**
     * A `Register-ArgumentCompleter` block, with one entry per command path.
     *
     * The table is generated from the live command tree, so a command that exists is a command
     * that completes. Aliases are included as they are: `var` completes exactly as `variable`
     * does, because both are things somebody may type.
     */
    private fun powershell(root: CommandLine): String {
        val entries = LinkedHashMap<String, List<String>>()

        fun walk(path: String, command: CommandLine) {
            val spec = command.commandSpec
            val subcommands = command.subcommands
                .filterValues { !it.commandSpec.usageMessage().hidden() }
                .keys.toList()
            // Long names only: a completion list of -h, -V and their long twins is noise.
            val options = spec.options()
                .filterNot { it.hidden() }
                .flatMap { it.names().toList() }
                .filter { it.startsWith("--") }
            entries[path] = (subcommands + options).distinct().sorted()
            command.subcommands.forEach { (name, sub) -> walk("$path $name", sub) }
        }
        walk(root.commandName, root)

        return buildString {
            appendLine("# Completion for ${root.commandName}. Generated by '${root.commandName} completion powershell'.")
            appendLine("# Add to your profile with:")
            appendLine("#   ${root.commandName} completion powershell | Out-String | Invoke-Expression")
            appendLine("#")
            appendLine("# Windows PowerShell does not call a native completer when the word being")
            appendLine("# completed is a bare - or --, so options complete after a space or from a")
            appendLine("# letter or two ('--l' finds '--limit'), but not from the dashes alone.")
            appendLine("Register-ArgumentCompleter -Native -CommandName ${root.commandName} -ScriptBlock {")
            appendLine("    param(\$wordToComplete, \$commandAst, \$cursorPosition)")
            appendLine()
            appendLine("    \$completions = @{")
            entries.forEach { (path, words) ->
                appendLine("        '$path' = @(${words.joinToString(", ") { "'$it'" }})")
            }
            appendLine("    }")
            appendLine()
            appendLine("    # The deepest command path the words so far spell out; an option ends it.")
            appendLine("    \$key = '${root.commandName}'")
            appendLine("    \$spoken = @(\$commandAst.CommandElements | ForEach-Object { \$_.ToString() })")
            appendLine("    if (\$spoken.Count -gt 1) {")
            appendLine("        foreach (\$word in \$spoken[1..(\$spoken.Count - 1)]) {")
            appendLine("            if (\$word.StartsWith('-')) { break }")
            appendLine("            if (\$completions.ContainsKey(\"\$key \$word\")) { \$key = \"\$key \$word\" } else { break }")
            appendLine("        }")
            appendLine("    }")
            appendLine()
            appendLine("    \$completions[\$key] | Where-Object { \$_ -like \"\$wordToComplete*\" } | ForEach-Object {")
            appendLine("        [System.Management.Automation.CompletionResult]::new(")
            appendLine("            \$_, \$_, 'ParameterValue', \$_)")
            appendLine("    }")
            appendLine("}")
        }
    }
}
