// Copyright (C) 2026 Michał Szymański
// SPDX-License-Identifier: AGPL-3.0-or-later
// See NOTICE for the additional term under section 7(b): the attribution this
// program prints must be preserved.

package io.mszymanski.orknux.cli

import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json
import java.io.IOException
import java.net.URI
import java.net.http.HttpClient
import java.net.http.HttpRequest
import java.net.http.HttpResponse
import java.net.http.HttpTimeoutException
import java.nio.charset.StandardCharsets
import java.nio.file.Files
import java.nio.file.Path
import java.time.Duration

/** Where a plugin is loaded. Not a mutation: a plugin arrives as a file. */
private const val PLUGINS_PATH = "/api/plugins"

/** Where the server writes one to start from. */
private const val TEMPLATE_PATH = "/api/plugins/template"

/** One function a plugin says it offers, as it declared it. */
@Serializable
data class PluginFunctionDeclaration(
    val name: String,
    val description: String? = null,
    val signature: String = "",
)

/**
 * A plugin as the installation holds it. `key` is what the plugin calls itself and is its
 * identity — loading the same key again replaces what is there — while `name` comes from the
 * filename it arrived as.
 */
@Serializable
data class Plugin(
    val id: String,
    val key: String,
    val name: String,
    val filename: String = "",
    val sizeBytes: Double = 0.0,
    val apiVersion: Int = 0,
    val declaredFunctions: List<PluginFunctionDeclaration> = emptyList(),
    val uploadedAt: String = "",
    val uploadedBy: String = "",
)

/**
 * What the server says about a load. `replaced` is true when a plugin of that key was already
 * there, and `provides` is what its functions are called now they are registered — a plugin's
 * `isTeammate` arrives as `teammates_isTeammate`.
 */
@Serializable
data class PluginLoaded(
    val plugin: Plugin,
    val replaced: Boolean = false,
    val provides: List<String> = emptyList(),
)

@Serializable
private data class Refusal(val message: String = "")

/**
 * Loads a plugin, which is the one thing this CLI sends as a file.
 *
 * `java.net.http` has no multipart of its own, so the body is assembled here: a boundary that
 * cannot occur in the content, one part named `file` as the server's `@RequestParam` expects,
 * and the closing delimiter. The bytes are sent exactly as they are on disk — the server
 * decodes them strictly as UTF-8 and refuses anything else, so re-encoding here would only
 * turn its clear refusal into a corrupted upload.
 */
class PluginClient(
    private val baseUrl: String,
    private val cookie: String,
    private val http: HttpClient = HttpClient.newBuilder()
        .connectTimeout(Duration.ofSeconds(10))
        .followRedirects(HttpClient.Redirect.NEVER)
        .build(),
) {

    /**
     * A plugin to start from, generated by the server.
     *
     * Generated there rather than carried here so that it cannot disagree with what this
     * installation accepts: the API version in it is the one that server runs, and the value
     * types are the ones it has. A template shipped inside `orkx` would describe a contract
     * that some other build judges.
     */
    fun template(): String {
        val request = HttpRequest.newBuilder(URI.create("$baseUrl$TEMPLATE_PATH"))
            .header("Accept", "text/javascript")
            .header("Cookie", cookie)
            .timeout(REQUEST_TIMEOUT)
            .GET()
            .build()

        val response = send(request)
        return when (response.statusCode()) {
            200 -> response.body()
            401 -> throw SessionExpired(
                "Your session at $baseUrl has expired. Run 'orkx login' to start another.",
            )
            403 -> throw OperationRefused("Generating a plugin requires the administrator role.")
            // This endpoint has no handler for being refused the administrator role, so that
            // arrives as a server error. Said as the possibility it is, not as a diagnosis.
            500 -> throw ServerUnreachable(
                "The server at $baseUrl answered 500. This is administrators only, which may be why.",
            )
            else -> throw ServerUnreachable(
                "The server at $baseUrl answered ${response.statusCode()} to the template request.",
            )
        }
    }

    fun load(file: Path): PluginLoaded {
        val bytes = try {
            Files.readAllBytes(file)
        } catch (e: IOException) {
            throw ServerUnreachable("Could not read $file: ${e.message}", e)
        }

        val boundary = "orkx-" + java.util.UUID.randomUUID()
        val request = HttpRequest.newBuilder(URI.create("$baseUrl$PLUGINS_PATH"))
            .header("Content-Type", "multipart/form-data; boundary=$boundary")
            .header("Accept", "application/json")
            .header("Cookie", cookie)
            .timeout(REQUEST_TIMEOUT)
            .POST(HttpRequest.BodyPublishers.ofByteArrays(parts(boundary, file.fileName.toString(), bytes)))
            .build()

        val response = send(request)
        return when (response.statusCode()) {
            200 -> decode(response.body())
            // Everything this endpoint refuses is about the file somebody chose, and it
            // answers with the sentence to show them.
            400 -> throw OperationRefused(refusal(response.body()))
            401 -> throw SessionExpired(
                "Your session at $baseUrl has expired. Run 'orkx login' to start another.",
            )
            403 -> throw OperationRefused("Loading a plugin requires the administrator role.")
            413 -> throw OperationRefused("The server would not accept a file that size.")
            else -> throw ServerUnreachable(
                "The server at $baseUrl answered ${response.statusCode()} to the upload.",
            )
        }
    }

    /**
     * The three pieces of a one-part body. Kept as separate arrays so the file's bytes are
     * never copied into a bigger one — a plugin is small, but a needless copy of somebody's
     * source is still a needless copy.
     */
    private fun parts(boundary: String, filename: String, content: ByteArray): List<ByteArray> {
        val header = buildString {
            append("--").append(boundary).append(CRLF)
            // The quotes are what the name is read out of, so a filename carrying one would
            // end the value early; the server only uses it for the plugin's name and refuses
            // anything not ending in .js or .mjs.
            append("Content-Disposition: form-data; name=\"file\"; filename=\"")
            append(filename.replace("\"", ""))
            append("\"").append(CRLF)
            append("Content-Type: text/javascript").append(CRLF)
            append(CRLF)
        }
        val footer = "$CRLF--$boundary--$CRLF"
        return listOf(header.toByteArray(StandardCharsets.UTF_8), content, footer.toByteArray(StandardCharsets.UTF_8))
    }

    private fun send(request: HttpRequest): HttpResponse<String> = try {
        http.send(request, HttpResponse.BodyHandlers.ofString())
    } catch (e: HttpTimeoutException) {
        throw ServerUnreachable("The server at $baseUrl did not answer in ${REQUEST_TIMEOUT.toSeconds()}s.", e)
    } catch (e: IOException) {
        throw ServerUnreachable("Cannot reach the server at $baseUrl: ${e.message ?: e::class.simpleName}", e)
    } catch (e: InterruptedException) {
        Thread.currentThread().interrupt()
        throw ServerUnreachable("Interrupted while waiting for the server at $baseUrl.", e)
    }

    private fun decode(body: String): PluginLoaded = try {
        json.decodeFromString<PluginLoaded>(body)
    } catch (e: Exception) {
        throw ServerUnreachable("The server at $baseUrl answered something unreadable: ${e.message}", e)
    }

    private fun refusal(body: String): String = try {
        json.decodeFromString<Refusal>(body).message.ifEmpty { body }
    } catch (_: Exception) {
        body.takeIf { it.isNotBlank() } ?: "That file could not be loaded."
    }

    private companion object {
        const val CRLF = "\r\n"
        val REQUEST_TIMEOUT: Duration = Duration.ofSeconds(60)
        val json = Json { ignoreUnknownKeys = true }
    }
}
